/*
==============================================
Typescript definitions for v1.3.2
==============================================

This file was automatically generated by Papyrus-2-Typescript.exe
https://github.com/CarlosLeyvaAyala/Papyrus-2-Typescript

*/
import * as sp from "skyrimPlatform";
var sn = sp.ConsoleUtil;
//-- Properties --------------------------------------
//-- Variables ---------------------------------------
//-- Functions ---------------------------------------
export var SetSelectedReference = function (a_reference) { return sn.SetSelectedReference(a_reference); };
export var ExecuteCommand = function (a_command) { return sn.ExecuteCommand(a_command); };
export var PrintMessage = function (a_message) { return sn.PrintMessage(a_message); };
export var GetVersion = function () { return sn.GetVersion(); };
export var ReadMessage = function () { return sn.ReadMessage(); };
export var GetSelectedReference = function () { return sn.GetSelectedReference(); };
