/*
==============================================
Typescript definitions for v1.3.2
==============================================

This file was automatically generated by Papyrus-2-Typescript.exe
https://github.com/CarlosLeyvaAyala/Papyrus-2-Typescript

*/

import * as sp from "skyrimPlatform"
import { ObjectReference } from "skyrimPlatform"

const sn = (sp as any).ConsoleUtil

//-- Properties --------------------------------------

//-- Variables ---------------------------------------

//-- Functions ---------------------------------------

export const SetSelectedReference = (a_reference: ObjectReference | null | undefined): void => sn.SetSelectedReference(a_reference)

export const ExecuteCommand = (a_command: string): void => sn.ExecuteCommand(a_command)

export const PrintMessage = (a_message: string): void => sn.PrintMessage(a_message)

export const GetVersion = (): number => sn.GetVersion()

export const ReadMessage = (): string => sn.ReadMessage()

export const GetSelectedReference = (): ObjectReference | null | undefined => sn.GetSelectedReference()
